### ISSUE TITLE
where is the 'tvm_runtime.py' in 'tvm_runtime_op/'？

### ISSUE THREAD

**Issue by zouzhene** [tobegit3hub/tftvm#1]
i cant find 'tvm_runtime.py' in 'tvm_runtime_op/'

**Comment by tobegit3hub** [comment]
The file was add in this commit https://github.com/tobegit3hub/tftvm/commit/e433597e81ba0119f1ed3370c21f57ae9aef8ae0 .

You can use `tvm_runtime_ops.py` instead of `tvm_runtime.py`.
