### ISSUE TITLE
Variable number of inputs and outputs

### ISSUE THREAD

**Issue by gmagogsfm** [tobegit3hub/tftvm#9]
First of all great project! This is really useful!

I am wondering if there are reasons behind hard-coding number of inputs to TvmDsoOp like:

https://github.com/tobegit3hub/tftvm/blob/master/src/tvm_dso_ops.cc

This might not work well when number of inputs is greater than 8 or when number of output is more than 1.

What do you think about using variadic inputs like this:
https://github.com/tensorflow/tensorflow/blob/240497c2b2058ed25b09308dd906441882ca7611/tensorflow/compiler/jit/ops/xla_ops.cc#L27

If you like this idea, maybe we can work together to implement this.

**Comment by tobegit3hub** [comment]
Thanks and it was implemented in tvm upstream.
